name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Backup .env
        run: |
          if [ -f .env ]; then
            mv .env /tmp/env_backup
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore .env
        run: |
          if [ -f /tmp/env_backup ]; then
            mv /tmp/env_backup .env
          fi

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Restart backend
        run: |
          pm2 restart backend || pm2 start src/server.js --name backend
          pm2 save
